### PR TITLE
Generate a model to run on the device

### PR DESCRIPTION
**Pull request by JuliaScythe**
@jaustin asked me to make this PR to show you the changes we made to ml-machine for using it with on-device models! This **isn't intended to be merged**, and it would be quite difficult to do so because we based our work on a commit before the removal of ml5.

(This pr should be based from a branch from commit 3284df8, as far as I can tell -- @jaustin mentioned he would create a branch for me to use on that commit, and I'll edit this PR to point to that branch once it's done -- until then it's probably best to look at the individual commits to see our changes.)

This project uses `ml4f` to compile the trained model to ARM bytecode, then writes the generated binary to a specific memory address in a precompiled firmware file (the source of which can be found at [JuliaScythe/microbit-gesture-ml](https://github.com/JuliaScythe/microbit-gesture-ml)), which passes the same data the frontend would normally receive to the model, and displays the output on the microbit display.

### CODE REVIEW

**Comment by jaustin** [comment]
@JuliaScythe thanks so much for making this PR (and the work you and your team did that his demonstrates!)

For the clarity of those that aren't familiar with the work you did, is it worth changing the PR title to something like "generate a model to run on the device" (as I parsed this as suggesting the model was actually generated on the device, at first)

For making a cleaner PR, does [oxford-project-base](https://github.com/microbit-foundation/cctd-ml-machine/tree/oxford-project-base) look like a branch at the commit you need?

**Comment by Karlo-Emilo** [comment]
I have just tested it. This is amazing! Thanks @JuliaScythe!

We will take a look at the code and see if we can make a version with the new ML-building implementation.

@JuliaScythe do you know of any issues with using a newer version of tensorflow? (ml5 is basically just a wrapper of an old tensorflow version)

**Comment by r59q** [comment]
This is amazing work, thank you!

I am amazed at how quickly this demo was realized and I'm curious as to it's potential. This is definitely something we will be using as a reference in the future. 

## The rest of the comment will be notes on the implications this change may bring, feel free to skip

> I have just tested it. This is amazing! Thanks @JuliaScythe!
> 
> We will take a look at the code and see if we can make a version with the new ML-building implementation.
> 
> @JuliaScythe do you know of any issues with using a newer version of tensorflow? (ml5 is basically just a wrapper of an old tensorflow version)

I think [ml4f](https://github.com/microsoft/ml4f) uses the TF.js model format. I do not believe the switch to Tensorflow from ml5 to be an issue we will have to revert or deal with, although my knowledge is limited. I am investigating, will update

**Comment by Karlo-Emilo** [comment]
@r59q 

To begin with, I think we should see this as an exploratory process. So not worry too much about how this feature will blend with the rest of the tool. Step one should be to test if we can make a version that is good and stable enough for a classroom activity. Step two would then be to test this version of a tool with teachers and students. So in the first phase, we should have this feature on its own branch and make a version that is dedicated to run the model on the micro:bit.

I agree, that It will become messy with all the different options for running and creating logic around the model. So we may consider to see this repo more as toolkit with which you can configure and build different versions of the tool. But that is a discussion for later.

Right now,  I think the focus should be to make a version that we can test in a classrooms to get some feedback and experiences with this feature.

**Comment by mmoskal** [comment]
I bumped tfjs in ml4f to v4.10 - it didn't require any changes and still seems to pass all the tests. Great work!

**Comment by r59q** [comment]
Im closing this, we will note it as a reference :)

**Pull request closed without merging**
