### PR TITLE
530 add axis highlighting visually2

### PR DESCRIPTION
**Pull request by r59q**

### CODE REVIEW

**Comment by Karlo-Emilo** [comment]
I get a type error, when I run 'npm run dev'

```
error TS5102: Option 'importsNotUsedAsValues' has been removed. Please remove it from your configuration.
  Use 'verbatimModuleSyntax' instead.

11:43:55 AM [vite] Pre-transform error: Error while preprocessing /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte - [svelte-preprocess] Encountered type error
error TS5102: Option 'importsNotUsedAsValues' has been removed. Please remove it from your configuration.
  Use 'verbatimModuleSyntax' instead.

11:43:56 AM [vite] Internal server error: Error while preprocessing /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte - [svelte-preprocess] Encountered type error
  Plugin: vite-plugin-svelte
  File: /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte
      at throwError (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)
      at throwTypescriptError (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)
      at transpileTs (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:215:47)
      at mixedImportsTranspiler (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:270:60)
      at transformer (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:344:11)
      at transform (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:46:12)
      at async /Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:117:29
      at async script (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:147:33)
      at async process_single_tag (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:285:21)
      at async Promise.all (index 1)
      at async replace_in_code (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/replace_in_code.js:69:23)
      at async process_tag (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:302:26)
      at async Module.preprocess (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:360:25)
      at async compileSvelte (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:89:20)
      at async TransformPluginContext.transform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:152:20)
      at async PluginContainer.transform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49096:18)
      at async loadAndTransform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
      at async viteTransformMiddleware (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:61881:24)
```

what I have tried to solve it:
- run 'npm i'
- Delete node_modules and package.json, run 'npm i'

A similar error occurs with 'npm run build'

**Comment by r59q** [comment]
> I get a type error, when I run 'npm run dev'
> 
> ```
> error TS5102: Option 'importsNotUsedAsValues' has been removed. Please remove it from your configuration.
>   Use 'verbatimModuleSyntax' instead.
> 
> 11:43:55 AM [vite] Pre-transform error: Error while preprocessing /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte - [svelte-preprocess] Encountered type error
> error TS5102: Option 'importsNotUsedAsValues' has been removed. Please remove it from your configuration.
>   Use 'verbatimModuleSyntax' instead.
> 
> 11:43:56 AM [vite] Internal server error: Error while preprocessing /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte - [svelte-preprocess] Encountered type error
>   Plugin: vite-plugin-svelte
>   File: /Users/au524252/Dev/aarhus-ml-machine/src/App.svelte
>       at throwError (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)
>       at throwTypescriptError (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)
>       at transpileTs (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:215:47)
>       at mixedImportsTranspiler (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:270:60)
>       at transformer (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/transformers/typescript.js:344:11)
>       at transform (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:46:12)
>       at async /Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:117:29
>       at async script (/Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte-preprocess/dist/autoProcess.js:147:33)
>       at async process_single_tag (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:285:21)
>       at async Promise.all (index 1)
>       at async replace_in_code (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/replace_in_code.js:69:23)
>       at async process_tag (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:302:26)
>       at async Module.preprocess (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/svelte/src/compiler/preprocess/index.js:360:25)
>       at async compileSvelte (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:89:20)
>       at async TransformPluginContext.transform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:152:20)
>       at async PluginContainer.transform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49096:18)
>       at async loadAndTransform (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
>       at async viteTransformMiddleware (file:///Users/au524252/Dev/aarhus-ml-machine/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:61881:24)
> ```
> 
> what I have tried to solve it:
> 
> * run 'npm i'
> * Delete node_modules and package.json, run 'npm i'
> 
> A similar error occurs with 'npm run build'

Sorry this was meant to be a draft, it's stiill WIP. I'm not sure why you are having this issue. Are you having this issue on main branch?

**Comment by Karlo-Emilo** [comment]
> Sorry this was meant to be a draft, it's stiill WIP. I'm not sure why you are having this issue. Are you having this issue on main branch?

I am not having this issue on main, but i get the same error on v3.3.

Setting '"verbatimModuleSyntax" in tsconfig to true and back to false again solved the issue.

The app loads with a syntax error in D3Plot.svelte, but is may just be because it is a draft?

**Comment by r59q** [comment]
> > Sorry this was meant to be a draft, it's stiill WIP. I'm not sure why you are having this issue. Are you having this issue on main branch?
> 
> I am not having this issue on main, but i get the same error on v3.3.
> 
> Setting '"verbatimModuleSyntax" in tsconfig to true and back to false again solved the issue.
> 
> The app loads with a syntax error in D3Plot.svelte, but is may just be because it is a draft?

Shouldn't be the case, I'll look into it

**Pull request merged**
